server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8082

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: stand300sub@gmail.com
    password: upqzjgjeqgrrridj
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com





  datasource:
    password: 1808318083
    url: jdbc:postgresql://localhost:5432/willSoon_0_1
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 692494463642-a3tfbpviq5ukuc3d5igrkajnd5jnqka6.apps.googleusercontent.com
            client-secret: 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
            scope: openid,email,profile
        provider:
          google:
            issuer-uri: https://accounts.google.com

  avatar:
    storage: "C:\\profile_images\\"